TERRITORY = {
    --Atlantic: North America
    Greenland= {guid="", nation=US, ipc=1},
    Canada= {guid="", nation=CW, ipc=5, vp={"ottawa"}},
    NewBrunswick= {guid="", nation=CW},
    Labrador= {guid="", nation=US, ipc=1},
    UnitedStates= {guid="", nation=US, ipc=20, vp={"washington"}},
    WestIndies= {guid="", nation=US, ipc=1},
    --Atlantic: South America
    Venezuela= {guid="", nation=BLANK, ipc=2, vp={"oil"}},
    BritishGuiana= {guid="", nation=UK},
    Suriname= {guid="", nation=DUTCH},
    FrenchGuiana= {guid="", nation=FRANCE},
    Brazil= {guid="", nation=PRO_ALLIES, ipc=2, vp={"rio de janeiro"}},
    BoliviaParaguay= {guid="", nation=BLANK},
    Argentina= {guid="", nation=PRO_AXIS, ipc=2},
    Uruguay= {guid="", nation=PRO_ALLIES},
    --Atlantic: English Channel
    Iceland= {guid="", nation=UK, ipc=1},
    Ireland= {guid="", nation=PRO_ALLIES},
    Scotland= {guid="", nation=UK, ipc=2},
    UnitedKingdom= {guid="", nation=UK, ipc=7, vp={"london"}},
    --Atlantic: Scandanavia
    Norway= {guid="", nation=GERMANY, ipc=3},
    Sweden= {guid="", nation=BLANK, ipc=3},
    Finland= {guid="", nation=PRO_AXIS, ipc=2},
    --Atlantic: West Europe
    Denmark= {guid="", nation=GERMANY, ipc=2},
    WesternGermany= {guid="", nation=GERMANY, ipc=5},
    HollandBelgium= {guid="", nation=GERMANY, ipc=3},
    --France
    NormandyBordeaux= {guid="", nation=FRANCE, ipc=2},
    France= {guid="", nation=FRANCE, ipc=4, vp={"paris"}},
    Vichy= {guid="", nation=FRANCE, ipc=3},
    --Central Europe
    Switzerland= {guid="", nation=BLANK, ipc=2},
    Germany= {guid="", nation=GERMANY, ipc=5, vp={"berlin"}},
    Poland= {guid="", nation=GERMANY, ipc=2, vp={"warsaw"}},
    SouthernGermany= {guid="", nation=GERMANY, ipc=4},
    SlovakiaHungary= {guid="", nation=GERMANY, ipc=3},
    --Baltics
    Romania= {guid="", nation=GERMANY, ipc=3, vp={"oil"}},
    Yugoslavia= {guid="", nation=PRO_ALLIES, ipc=2},
    Bulgaria= {guid="", nation=PRO_AXIS, ipc=1},
    Albania= {guid="", nation=ITALY, ipc=1},
    --Iberian Peninsula
    GaliciaNavarra= {guid="", nation=SPAIN},
    Aragon= {guid="", nation=SPAIN, ipc=1},
    Castilla= {guid="", nation=SPAIN, ipc=1},
    Portugal= {guid="", nation=PORTUGAL, ipc=1},
    Gibraltar= {guid="", nation=UK},
    Azores= {guid="", nation=PORTUGAL},
    --Mediterranean
    Greece= {guid="", nation=PRO_ALLIES, ipc=2},
    NorthernItaly= {guid="", nation=ITALY, ipc=4},
    SouthernItaly= {guid="", nation=ITALY, ipc=3, vp={"rome"}},
    Sardinia= {guid="", nation=ITALY},
    Sicily= {guid="", nation=ITALY, ipc=1},
    Crete= {guid="", nation=PRO_ALLIES},
    Cyprus= {guid="", nation=UK},
    Malta= {guid="", nation=UK, ipc=1},
    --North Africa
    Casablanca= {guid="", nation=FRANCE},
    Morocco= {guid="", nation=FRANCE, ipc=1},
    SpanishMorocco= {guid="", nation=PRO_AXIS},
    Algeria= {guid="", nation=FRANCE, ipc=1},
    Tunisia= {guid="", nation=FRANCE, ipc=1},
    ItalianLibya= {guid="", nation=ITALY, ipc=1},
    Tobruk= {guid="", nation=ITALY},
    ElAlamein= {guid="", nation=UK},
    Egypt= {guid="", nation=UK, ipc=2, vp={"egypt"}},
    --West Africa
    RioDeOro= {guid="", nation=SPAIN},
    FrenchWestAfrica= {guid="", nation=FRANCE, ipc=1},
    SierraLeone= {guid="", nation=UK, ipc=1},
    GoldCoast= {guid="", nation=UK, ipc=1},
    Nigeria= {guid="", nation=UK, ipc=1},
    --Central Africa
    FrenchEquatorialAfrica= {guid="", nation=FRANCE, ipc=1},
    AngloEgyptianSudan= {guid="", nation=UK, ipc=1},
    BelgianCongo= {guid="", nation=UK, ipc=2, vp={"resources"}},
    Tanganyika= {guid="", nation=UK, ipc=1},
    --East Africa
    Ethiopia= {guid="", nation=ITALY, ipc=1},
    BritishSomaliland= {guid="", nation=UK},
    ItalianSomaliland= {guid="", nation=ITALY},
    Kenya= {guid="", nation=UK, ipc=1},
    FrenchMadagascar= {guid="", nation=FRANCE, ipc=1},
    --South Africa
    Angola= {guid="", nation=PORTUGAL, ipc=1},
    SouthWestAfrica= {guid="", nation=CW, ipc=1},
    SouthAfrica= {guid="", nation=CW, ipc=2},
    Rhodesia= {guid="", nation=UK, ipc=1},
    Mozambique= {guid="", nation=PORTUGAL, ipc=1},
    --Middle East
    SaudiArabia= {guid="", nation=BLANK, ipc=2, vp={"oil"}},
    TransJordan= {guid="", nation=UK, ipc=1},
    LebanonSyria= {guid="", nation=FRANCE, ipc=1},
    Marmara= {guid="", nation=BLANK, ipc=1},
    CentralAnatolia= {guid="", nation=BLANK},
    EasternAnatolia= {guid="", nation=BLANK},
    Iraq= {guid="", nation=PRO_AXIS, ipc=2, vp={"oil"}},
    NorthernIran= {guid="", nation=PRO_AXIS, ipc=1},
    Iran= {guid="", nation=PRO_AXIS, ipc=2, vp={"oil"}},
    Afghanistan= {guid="", nation=BLANK},
    --Arctic: Russia
    Vyborg= {guid="", nation=USSR},
    Karelia= {guid="", nation=USSR, ipc=1},
    Leningrad= {guid="", nation=USSR, ipc=2, vp={"leningrad"}},
    Archangel= {guid="", nation=USSR, ipc=1},
    Nenetsia= {guid="", nation=USSR},
    --Eastern Europe: Russia
    EstoniaLatvia= {guid="", nation=USSR},
    Lithuania= {guid="", nation=USSR, ipc=1},
    EasternPoland= {guid="", nation=USSR, ipc=1},
    Bessarabia= {guid="", nation=USSR, ipc=1},
    Ukraine= {guid="", nation=USSR, ipc=2, vp={"resources"}},
    WesternUkraine= {guid="", nation=USSR, ipc=1},
    PripetMarshes= {guid="", nation=USSR},
    Belarus= {guid="", nation=USSR, ipc=1},
    Smolensk= {guid="", nation=USSR, ipc=1},
    Bryansk= {guid="", nation=USSR, ipc=1},
    --Northern Russia
    Vologda= {guid="", nation=USSR, ipc=1},
    Novosibirsk= {guid="", nation=USSR, ipc=1},
    Urals= {guid="", nation=USSR, ipc=2, vp={"resources"}},
    Tunguska= {guid="", nation=USSR, ipc=1},
    --Central Russia
    Kaluga= {guid="", nation=USSR, ipc=1},
    Moscow= {guid="", nation=USSR, ipc=5, vp={"moscow"}},
    Tula= {guid="", nation=USSR, ipc=1},
    Samara= {guid="", nation=USSR, ipc=1},
    Tambov= {guid="", nation=USSR, ipc=1},
    Kursk= {guid="", nation=USSR, ipc=1},
    --South Russia
    Rostov= {guid="", nation=USSR, ipc=2},
    Stalingrad= {guid="", nation=USSR, ipc=2, vp={"stalingrad"}},
    KazakhSSR= {guid="", nation=USSR, ipc=1},
    TurkmenSSR= {guid="", nation=USSR, ipc=1},
    Caucasus= {guid="", nation=USSR, ipc=2, vp={"oil", "resources"}},
    --Siberia
    Evenkiyskiy= {guid="", nation=USSR},
    Yenisey= {guid="", nation=USSR},
    YakutSSR= {guid="", nation=USSR},
    Buryatia= {guid="", nation=USSR},
    Sakha= {guid="", nation=USSR, ipc=1},
    Siberia= {guid="", nation=USSR, ipc=2, vp={"resources"}},
    SovietFarEast= {guid="", nation=USSR},
    Amur= {guid="", nation=USSR, ipc=1},
    --Mongolia
    Olgiy= {guid="", nation=MONGOLIA},
    Dzavhan= {guid="", nation=MONGOLIA, ipc=1},
    Dornod= {guid="", nation=MONGOLIA},
    Dornogobi= {guid="", nation=MONGOLIA},
    --Japan: Mainland
    KurilIslands= {guid="", nation=JAPAN},
    Hokkaido= {guid="", nation=JAPAN, ipc=2},
    Japan= {guid="", nation=JAPAN, ipc=12, vp={"tokyo"}},
    Korea= {guid="", nation=JAPAN, ipc=2},
    Manchuria= {guid="", nation=JAPAN, ipc=2, vp={"resources"}},
    --Pacific: Japanese Islands
    IwoJima= {guid="", nation=JAPAN, ipc=1},
    Okinawa= {guid="", nation=JAPAN, ipc=1},
    Taiwan= {guid="", nation=JAPAN, ipc=1},
    Hainan= {guid="", nation=JAPAN},
    Marianas= {guid="", nation=JAPAN},
    MarshallIslands= {guid="", nation=JAPAN},
    CarolineIslands= {guid="", nation=JAPAN},
    Palau= {guid="", nation=JAPAN},
    --China: East Coast
    Jehol= {guid="", nation=JAPAN, ipc=1},
    Shansi= {guid="", nation=JAPAN, ipc=1},
    Shantung= {guid="", nation=JAPAN, ipc=2},
    Kiangsu= {guid="", nation=JAPAN, ipc=2, vp={"shanghai"}},
    Fukien= {guid="", nation=JAPAN, ipc=1},
    --North China
    Sinkiang= {guid="", nation=BLANK, ipc=1},
    Qinghai= {guid="", nation=CHINA, ipc=1},
    Kansu= {guid="", nation=CHINA, ipc=1},
    Shensi= {guid="", nation=CHINA, ipc=1},
    Honan= {guid="", nation=CHINA, ipc=1},
    --Southwest China
    Tibet= {guid="", nation=BLANK, ipc=2, vp={"resources"}},
    Szechwan= {guid="", nation=CHINA, ipc=1},
    Kweichow= {guid="", nation=CHINA, ipc=1},
    Yunan= {guid="", nation=CHINA, ipc=1},
    --Southeast China
    Hopeh= {guid="", nation=CHINA, ipc=2},
    Anwhei= {guid="", nation=CHINA, ipc=1},
    Hunan= {guid="", nation=CHINA, ipc=1},
    Kwangsi= {guid="", nation=CHINA, ipc=1},
    Kwangtung= {guid="", nation=UK, ipc=3, vp={"hong kong"}},
    --South East Asia
    NorthIndochina= {guid="", nation=FRANCE, ipc=1},
    FrenchIndochina= {guid="", nation=FRANCE, ipc=2},
    Thailand= {guid="", nation=PRO_AXIS= ipc=1},
    Malaya= {guid="", nation=UK, ipc=2},
    EastBurma= {guid="", nation=UK, ipc=1},
    Burma= {guid="", nation=UK, ipc=1},
    --India
    India= {guid="", nation=UK, ipc=6, vp={"calcutta"}},
    WestIndia= {guid="", nation=UK, ipc=2},
    Ceylon= {guid="", nation=UK},
    --Spice Islands
    Sumatra= {guid="", nation=DUTCH, ipc=2, vp={"oil"}},
    Java= {guid="", nation=DUTCH, ipc=2, vp={"oil"}},
    Borneo= {guid="", nation=UK, ipc=2, vp={"oil"}},
    Celebes= {guid="", nation=DUTCH, ipc=2, vp={"oil"}},
    DutchNewGuinea= {guid="", nation=DUTCH, ipc=1, vp={"oil"}},
    --Pacific: US Islands
    Philippines= {guid="", nation=US, ipc=2, vp={"manila"}},
    Guam= {guid="", nation=US},
    Midway= {guid="", nation=US},
    WakeIsland= {guid="", nation=US},
    HawaiianIslands= {guid="", nation=US, ipc=2, vp={"honolulu"}},
    JohnstonIsland= {guid="", nation=US},
    LineIslands= {guid="", nation=US},
    --Pacific: Oceania
    GilbertIslands= {guid="", nation=UK},
    Samoa= {guid="", nation=CW},
    Fiji= {guid="", nation=UK},
    NewHebrides= {guid="", nation=FRANCE},
    SolomonIslands= {guid="", nation=CW},
    NewBritain= {guid="", nation=CW},
    NewGuinea= {guid="", nation=CW},
    --Australia
    WesternAustralia= {guid="", nation=CW, ipc=2, vp={"resources"}},
    NorthernTerritory= {guid="", nation=CW, ipc=1},
    SouthAustralia= {guid="", nation=CW},
    Queensland= {guid="", nation=CW, ipc=2},
    NewSouthWales= {guid="", nation=CW, ipc=3, vp={"sydney"}},
    Victoria= {guid="", nation=CW},
    NewZealand= {guid="", nation=CW, ipc=1},
    --Atlantic: North America
    CentralAmerica= {guid="", nation=US, ipc=2},
    Mexico= {guid="", nation=US, ipc=5},
    WesternUnitedStates= {guid="", nation=US, ipc=20, vp={"san francisco"}},
    WesternCanada= {guid="", nation=CW, ipc=2},
    Alaska= {guid="", nation=US, ipc=2, vp={"juneau"}},
    AleutianIslands= {guid="", nation=US},
    --Atlantic: South America
    Colombia= {guid="", nation=PRO_ALLIES},
    EcuadorPeru= {guid="", nation=BLANK},
    Chile= {guid="", nation=BLANK, ipc=2}
}   