UNITS= {
    [GERMANY]= {
        [INF]= {guid="756da2"},
        [ART]= {guid="90eacb"},
        [MECH]= {guid="684469"},
        [TANK]= {guid="80c25e"},
        [FTR]= {guid="cf8b6d"},
        [TAC]= {guid="38876b"},
        [SBR]= {guid="5a68a8"},
        [TPT]= {guid="572252"},
        [SUB]= {guid="249870"},
        [DTR]= {guid="3c0390"},
        [CSR]= {guid="78a023"},
        [BTS]= {guid="21fbc4"},
        [ACC]= {guid="186d81"},
        [AAA]= {guid="f2f2ce"}
    },
    [JAPAN]= {
        [INF]= {guid="ecb4e8"},
        [ART]= {guid="9ada7f"},
        [MECH]= {guid="ece7ab"},
        [TANK]= {guid="d632ad"},
        [FTR]= {guid="a81778"},
        [TAC]= {guid="e4c6c9"},
        [SBR]= {guid="d6c20b"},
        [TPT]= {guid="e20b56"},
        [SUB]= {guid="107c80"},
        [DTR]= {guid="2ef771"},
        [CSR]= {guid="4ff642"},
        [BTS]= {guid="6b2057"},
        [ACC]= {guid="e75fd0"},
        [AAA]= {guid="8aa94b"}
    },
    [US]= {
        [INF]= {guid="5b710c"},
        [ART]= {guid="f6c61d"},
        [MECH]= {guid="5037aa"},
        [TANK]= {guid="9be76c"},
        [FTR]= {guid="7ac8bc"},
        [TAC]= {guid="dd76a7"},
        [SBR]= {guid="b486b9"},
        [TPT]= {guid="5aee89"},
        [SUB]= {guid="412fa6"},
        [DTR]= {guid="56153d"},
        [CSR]= {guid="537fd9"},
        [BTS]= {guid="0cbef2"},
        [ACC]= {guid="a95d54"},
        [AAA]= {guid="e85443"}
    },
    [UK]= {
        [INF]= {guid="0afc00"},
        [ART]= {guid="728b65"},
        [MECH]= {guid="ff32d7"},
        [TANK]= {guid="d602e7"},
        [FTR]= {guid="b41597"},
        [TAC]= {guid="81033c"},
        [SBR]= {guid="4c2c09"},
        [TPT]= {guid="f8b47d"},
        [SUB]= {guid="b6b465"},
        [DTR]= {guid="36f16e"},
        [CSR]= {guid="161ffd"},
        [BTS]= {guid="9fe72b"},
        [ACC]= {guid="7682d6"},
        [AAA]= {guid="2022b4"}
    },
    [CHINA]= {
        [INF]= {guid="5aaf0a"},
        [CAV]= {guid= "641ef3"},
        [ART]= {guid="1b4512"},
        [TANK]= {guid="6fec49"},
        [FTR]= {guid="dc988a"},
        [AAA]= {guid="c48b10"}
    },
    [ITALY]= {
        [INF]= {guid="598e5e"},
        [ART]= {guid="e51027"},
        [MECH]= {guid="9f892c"},
        [TANK]= {guid="328712"},
        [FTR]= {guid="3c8677"},
        [TAC]= {guid="baebb3"},
        [SBR]= {guid="709c08"},
        [TPT]= {guid="c8c9d8"},
        [SUB]= {guid="ad762c"},
        [DTR]= {guid="99b39e"},
        [CSR]= {guid="a8a383"},
        [BTS]= {guid="cf0bd6"},
        [ACC]= {guid="8873c6"},
        [AAA]= {guid="b1a2bd"}
    },
    [CW]= {
        [INF]= {guid="f2298a"},
        [ART]= {guid="24bb6f"},
        [MECH]= {guid="ad14cf"},
        [TANK]= {guid="48a70d"},
        [FTR]= {guid="e24d4a"},
        [TAC]= {guid="f0d1f1"},
        [SBR]= {guid="7ec30d"},
        [TPT]= {guid="d3530a"},
        [SUB]= {guid="f1cf3e"},
        [DTR]= {guid="5795bc"},
        [CSR]= {guid="41a9b1"},
        [BTS]= {guid="bfca13"},
        [ACC]= {guid="ce75ec"},
        [AAA]= {guid="bb7dbb"}
    },
    [FRANCE]= {
        [INF]= {guid="c1c3db"},
        [ART]= {guid="8ed142"},
        [MECH]= {guid="173a66"},
        [TANK]= {guid="8f6ddb"},
        [FTR]= {guid="1acca6"},
        [TAC]= {guid="2c75e9"},
        [SBR]= {guid="208e90"},
        [TPT]= {guid="df51f8"},
        [SUB]= {guid="014d3a"},
        [DTR]= {guid="2aaff7"},
        [CSR]= {guid="0a4d9a"},
        [BTS]= {guid="da2de7"},
        [ACC]= {guid="9484f6"},
        [AAA]= {guid="92b7b7"}
    },
    [USSR]= {
        [INF]= {guid="fc872a"},
        [ART]= {guid="97d28c"},
        [MECH]= {guid="2dac87"},
        [TANK]= {guid="6c7a46"},
        [FTR]= {guid="f91691"},
        [TAC]= {guid="012bae"},
        [SBR]= {guid="c429cf"},
        [TPT]= {guid="98dfaf"},
        [SUB]= {guid="753508"},
        [DTR]= {guid="fe876b"},
        [CSR]= {guid="0cd722"},
        [BTS]= {guid="38030b"},
        [ACC]= {guid="f32334"},
        [AAA]= {guid="b2c29a"}
    },
}

-- [GERMANY]= {
--     [INF]= {guid=""},
--     [ART]= {guid=""},
--     [MECH]= {guid=""},
--     [TANK]= {guid=""},
--     [FTR]= {guid=""},
--     [TAC]= {guid=""},
--     [SBR]= {guid=""},
--     [TPT]= {guid=""},
--     [SUB]= {guid=""},
--     [DTR]= {guid=""},
--     [CSR]= {guid=""},
--     [BTS]= {guid=""},
--     [ACC]= {guid=""},
--     [AAA]= {guid=""}
-- }